//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliment_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_GuestQuery
    {
        public int Id { get; set; }
        public Nullable<int> QueryTypeId { get; set; }
        public string QueryTypeValue { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string BlockName { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string AreaName { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<int> FourDigitPin { get; set; }
        public string Address { get; set; }
        public string QueryHeading { get; set; }
        public string QueryDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifyBy { get; set; }
        public string AdminResponseMessage { get; set; }
    }
}
