//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliment_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_UserMessage
    {
        public int Id { get; set; }
        public string MessageSubject { get; set; }
        public string MessageBody { get; set; }
        public string FileName { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public string UserFullName { get; set; }
        public string ReplyMessage { get; set; }
        public string ReplyFileName { get; set; }
    }
}
