//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliment_DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliEntities : DbContext
    {
        public PoliEntities()
            : base("name=PoliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PL_Admin> PL_Admin { get; set; }
        public virtual DbSet<PL_Block> PL_Block { get; set; }
        public virtual DbSet<PL_User> PL_User { get; set; }
        public virtual DbSet<PL_UserMessage> PL_UserMessage { get; set; }
        public virtual DbSet<PL_AdminMessage> PL_AdminMessage { get; set; }
        public virtual DbSet<PL_FrontEndImage> PL_FrontEndImage { get; set; }
        public virtual DbSet<PL_ManageHomeScreen> PL_ManageHomeScreen { get; set; }
        public virtual DbSet<PL_AdminOtp> PL_AdminOtp { get; set; }
        public virtual DbSet<PL_AdminNews> PL_AdminNews { get; set; }
        public virtual DbSet<PL_UserOtp> PL_UserOtp { get; set; }
        public virtual DbSet<PL_GuestQuery> PL_GuestQuery { get; set; }
        public virtual DbSet<PL_AdminDevelopmentWork> PL_AdminDevelopmentWork { get; set; }
        public virtual DbSet<PL_ContactMessage> PL_ContactMessage { get; set; }
        public virtual DbSet<PL_FrontEndVideo> PL_FrontEndVideo { get; set; }
        public virtual DbSet<PL_VotingSurvey> PL_VotingSurvey { get; set; }
        public virtual DbSet<PL_VoiceCallDetails> PL_VoiceCallDetails { get; set; }
        public virtual DbSet<SentSmsDetail> SentSmsDetails { get; set; }
        public virtual DbSet<PL_AdminOtpRecord> PL_AdminOtpRecord { get; set; }
        public virtual DbSet<PL_UserOtpRecord> PL_UserOtpRecord { get; set; }
        public virtual DbSet<PL_UserBankDetails> PL_UserBankDetails { get; set; }
        public virtual DbSet<PL_VidhanSabhaVoters> PL_VidhanSabhaVoters { get; set; }
        public virtual DbSet<PL_Area> PL_Area { get; set; }
    }
}
